service: default
runtime: go1.12
env: flex
instance_class: F2
# GCP Config
#env_variables:
#  PROJECT_ID: $PROJECT_ID
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 20

network:
    forwarded_ports:
      - 50051/tcp